// src/components/ConsentPage.js
import React from 'react';
import { Container, Button } from 'react-bootstrap';

const ConsentPage = ({ onConsent, hasConsented }) => {
  return (
    <Container>
      <div className="mt-4" style={styles.container}>
        <h1>GlassChords</h1>
        <h2>A transparent and interpretable AI chord generator</h2> <br />
        <h3>Participant Information and Consent</h3> <br />
        
        <p style={styles.justifiedText}>
            <strong>Purpose of this study:</strong> This study aims to investigate how a controllable chord-generating AI model can impact users' understanding of how AI creates music, as part of ongoing research in Explainable AI (XAI). <strong>Before taking part in this study, please read the{' '}
            <a href="https://drive.google.com/file/d/15lt6-fikeXsA7cc8St4Cw3bPGi6F69qC/view?usp=drive_link" target="_blank" rel="noopener noreferrer">Participant Information Sheet</a> and the{' '}
            <a href="https://drive.google.com/file/d/1oM04Zdn-BjJ2y9lP-1aJzCczy9DTwDon/view?usp=drive_link" target="_blank" rel="noopener noreferrer">Consent Form</a>.</strong>
        </p>
        
        <p style={styles.justifiedText}>
            <strong>What will participating in this study involve?</strong> Participating in this study involves interacting with a website-based AI chord generator, where you will have the opportunity to generate chord sequences and explore different settings of the AI. The study aims to enhance transparency and user comprehension of AI-generated music. <strong>The study will take approximately 10 minutes. Please ensure you are wearing headphones or have access to speakers before you begin.</strong>
        </p>
        
        <p style={styles.justifiedText}><strong>Part 1:</strong> The first part of the study will introduce you to a fixed version of the AI chord generator, where you can create and listen to chord sequences generated by the model.</p>
        
        <p style={styles.justifiedText}><strong>Part 2:</strong> In the second part, you will use a controllable version of the AI chord generator, where you can adjust various settings to observe how they affect the generated chords.</p>
        
        <p style={styles.justifiedText}>
            <strong>Consent:</strong> To participate in this research, you must provide your consent. By clicking the "Next" button below, you confirm that you understand the study's purpose and procedures, and you consent to participate. Your participation will involve interacting with the AI chord generator and completing a short survey. You understand that your participation is voluntary and that you can withdraw at any time without penalty. You also confirm that you are over 18 years old and that you agree to the terms of this study.
        </p>

        {hasConsented ? (
            <p style={styles.alreadyConsented}>
            <strong>You have already consented. If you do not wish to move forward with the research, please close the webpage.</strong>
            </p>
        ) : (
            <Button variant="primary" onClick={onConsent}>Next</Button>
        )}
      </div>
      <br />
    </Container>
  );
};

const styles = {
  container: {
    borderRadius: '15px',
    padding: '20px',
    boxShadow: '0px 4px 0px rgba(0, 0, 0, 0.1)',
    backgroundColor: '#e7edfe',
  },
  justifiedText: {
    textAlign: 'justify',
  },
  alreadyConsented: {
    color: 'red',
    textAlign: 'center',
    marginTop: '20px',
    marginBottom: '6px',
  },
};

export default ConsentPage;
